### ISSUE TITLE
Create a Crypto related Starter Site

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/templates-patterns-collection#128]

**Comment by JohnPixle** [comment]
There are many ways to approach the niche, but based on the [Slack discussion](https://vertistudio.slack.com/archives/CH8BQSMAM/p1637846214032800) I think it would be a good idea to start simple with an NFT Project. Then we can expand to a crypto-business. Our color palette for dark and light UIs is a great fit for the niche as well. 

### Context
Basically an NFT Project will use the website to showcase the art, some token metrics, and other data. We can leave the technical stuff (logging in with wallet/ token minting etc) since these will require some web 3.0 coding.
 
### Examples: 

https://www.themekaverse.com/
https://alpharonins.app/
https://boredapeyachtclub.com/#/home


**Common Sections:**
- Roadmap
- Team
- Galleries
- FAQ
- Socials (discord)
- CTA to buy collection at marketplaces 
- Countdown until drop


I believe we can start an **/nft-project demo** and take it from there. It might be a good idea to involve Andrea in the artistic part if she is interested. I will reach out to her. I should also start something in Figma to use as a starting point.

**Comment by mghenciu** [comment]
I'll close this one, as we released the NFT - Illustrator demo, both for Gutenberg and Elementor.
https://demosites.io/nft-illustrator/
https://demosites.io/nft-illustrator-gb

We can explore later a different Crypto related theme, is the case.
