### ISSUE TITLE
scrollbar shows up when more than 3 plugins are installed

### ISSUE THREAD

**Issue by selul** [Codeinwp/templates-patterns-collection#146]
### Description:
Right now a scrollbar is showing up when more than 3 plugins are installed. This might create some friction until the import is performed so we can think of some design where they look more compact. 

___

**Comment by selul** [comment]
https://vertis.d.pr/kF1Evm on Neve original in Gutenberg

**Comment by ineagu** [comment]
in this specific case as a note we can drop wpforms since we'll have forms in otter.

**Comment by selul** [comment]
Agree with this.

**Comment by preda-bogdan** [comment]
@Codeinwp/design-team can you help me when you have some time with some suggestions on how we can change the import modal so that we can better accommodate multiple plugins listed there for the future?

I was thinking of having the footer of the modal with the import buttons sticky so that it is always visible. A suggestion here, don't know if it is a good option, we could have the Plugins section closed by default and just display a pill with the number of plugins that will be installed. If the user needs more information he can open the accordion and toggle the plugins on or off.

While waiting for input from you I will filter `wpforms` from `demo-export` as it is my understanding that they are not used anymore on any imports: https://github.com/Codeinwp/demo-data-exporter/issues/133#issuecomment-1294975714

List of Starter sites that used WP Forms: https://www.notion.so/themeisle/Replace-WP-Forms-with-Otter-Form-Block-from-the-existing-sites-e927982ecf1a4e30836ed7c0205a62ce


Let me know if you have any feedback. Thank you!

**Comment by preda-bogdan** [comment]
@irinelenache I've removed `wpforms-lite` from all starter sites on staging. When you have some time can you please check that the wpforms is no longer suggested on import and that there is no issue with sites that previously used this. You can use this list: https://www.notion.so/themeisle/Replace-WP-Forms-with-Otter-Form-Block-from-the-existing-sites-e927982ecf1a4e30836ed7c0205a62ce

Once you confirm this I can do the same for the live server. (demosites.io)

Thank you!

**Comment by mghenciu** [comment]
For the Web Agency one, I think we still use WP Forms as we have a Contact form there >> https://demosites.io/web-agency-gb/web-agency-gb-contact-us/

This demos **is not using Otter at all**, that's why we went for WPForms.
On all other demos, all the forms should be already converted to Otter forms 🚀

**Comment by ineagu** [comment]
Any reason to not use otter?

**Comment by ineagu** [comment]
I think it was a decision made a long time ago when otter was more of an mvp

**Comment by ineagu** [comment]
Yep, because otter perf was questionable :) now is not i think

**Comment by preda-bogdan** [comment]
For consistency's sake, I would try to use Otter if possible. If not possible I can add `wpforms` back just for `web-agency-gb`.
@mghenciu What do you think can we also use Otter here?

**Comment by mghenciu** [comment]
Yes, **I'll convert the Contact form this week**, and will post an update here.

**Comment by mghenciu** [comment]
All good, Bogdan, **I've replaced the WPForm with an Otter Form**, deactivated the WP Forms plugin and changed the settings in Demo exporter:
<img width="1729" alt="Screenshot 2022-11-03 at 16 20 43" src="https://user-images.githubusercontent.com/52494172/199746171-105f1159-5ceb-4298-90b4-bf0e223ccfa2.png">

___
Regarding the **Modal having the Scroll**, I think another solution could be to add the fit-content property to the Modal.
Not sure if this can backfire in any way:

https://user-images.githubusercontent.com/52494172/199755688-c848524d-a041-4223-82f1-e1762ff3c14b.mov



___
Or we can definitely use what you proposed Bogdan, having the Plugins Panel closed by default, with a small notice:
### Notice on Top
<img width="854" alt="image" src="https://user-images.githubusercontent.com/52494172/199756672-511c02cf-d599-44cd-bed7-c5e4a1b7aedb.png">


### Notice on Bottom
<img width="894" alt="image" src="https://user-images.githubusercontent.com/52494172/199756528-b6378205-5811-462d-bb84-7a4b1cbf987f.png">


@JohnPixle do you have any thoughts UIX wise, on this? not urgent at all

**Comment by irinelenache** [comment]
@preda-bogdan @mghenciu Checked the **web agency** starter site (the version with Otter is available directly on demosites, the wpforms version is still available on staging) and the Otter form is working as expected 👍 There are a few issues with the spacings that happen on import:

The bottom spacing for almost all images is different in demosites and import
- On the **homepage** - [demosites](https://vertis.d.pr/i/crPgAa) / [import](https://vertis.d.pr/i/moyMMs) , [demosites](https://vertis.d.pr/i/HcCXDU) / [import](https://vertis.d.pr/i/Gx0Mvo)
- On the **about us** page - [demosites](https://vertis.d.pr/i/SYekjV) / [import](https://vertis.d.pr/i/3J1CLM) , [demosites](https://vertis.d.pr/i/ykEXhW) / [import](https://vertis.d.pr/i/YKFBBS)
- On the **portfolio** page - [import](https://vertis.d.pr/i/fTwllP) , [import](https://vertis.d.pr/i/TA86oI)
- On the **portfolio single** page - [import](https://vertis.d.pr/i/QQSHut)
- On the **contact us** page - [import](https://vertis.d.pr/i/zR2NfT)

**Comment by mghenciu** [comment]
> The bottom spacing for almost all images is different in demosites and import

That may be related to the WP version or Gutenberg version. As on demosites all the images have a default **bottom-margin** **added by Core**:
<img width="1720" alt="Screenshot 2022-11-09 at 13 11 48" src="https://user-images.githubusercontent.com/52494172/200815813-6eb8a2a1-34ac-46f2-94d7-128f67650ab6.png">



while on a Test Instance, that bottom-margin is missing:
<img width="1717" alt="Screenshot 2022-11-09 at 13 12 15" src="https://user-images.githubusercontent.com/52494172/200815861-f80ae497-31cd-47de-9502-df11b80bd7c2.png">

**Comment by preda-bogdan** [comment]
An update here the wpforms is also removed from production now.
