### ISSUE TITLE
Remove Neve dependency from TPC / Phase 2

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/templates-patterns-collection#161]
### Description:

Remove Neve dependency from Neve to allow TPC to work as a stand-alone.
Requirements:
- [x] Have an independent license
- [x] Allow usage of Cloud Library with any theme

**Comment by ineagu** [comment]
another way to look at it is that in phase 2 the product should be able to compete with kadence cloud or https://assistant.pro

**Comment by cristian-ungureanu** [comment]
Hey @preda-bogdan, @selul, @ineagu.

I've made some research on Kadence and Assistant Pro and I think we're far from competing with them at this point. What I would focus on in this phase would be to allow the usage of Cloud Library with any theme, implement a licensing system and make sure that page templates are working well with other themes.

For licensing, I think we can follow the same process as we had for Sparks. @mskapusuz can help with insights and things we should think about. In terms of UI, I was thinking of adding a button and a dropdown menu where the user can enter their license https://d.pr/H3Pko7

Once the license is activated, we will give access to the cloud part and also enable the button to save a template in cloud.

We will need some help from @Codeinwp/design-team to make sure the page templates we have are working smoothly with other themes as well. This is what one of our templates looks like with other themes https://vertis.d.pr/Fysqy9. We need to edit each one of those templates and make sure we're not relying on the theme's settings (fonts/font sizes/colors) and define those inside the template.

Once we achieve that, I think we can explore other features. In Assistant Pro I saw they allow multiple data types to be stored in the cloud. From Kadence I saw they externalize the templates part so an agency could create its own templates and sell them to their clients.  There are plenty of functionalities that we can add but I would start a discussion about that in another iteration.

Let me know what you guys think.

**Comment by selul** [comment]
Thanks for looking into it, Cristi. The plan is good, I dont think we need any migration, the functionality is in TPC and we just need to:
- sell individual license for tpc where they have access to saving and loading from cloud
- allow Neve license to use this new product.

Basically this product wont have a phisical pro version, will only grant access to the templates cloud thru TPC plugin, which already have.

Maybe Im missing something @preda-bogdan @cristian-ungureanu, let me know if Im wrong.

**Comment by selul** [comment]
yep, exactly.

**Comment by preda-bogdan** [comment]
@selul 
An update here, previously I added the licensing logic inside TPC, but as discussed this concern should be part of Templates Cloud.

As a result, I managed to set up locally the EDD with Templates Cloud so that I can test all endpoints and be able to generate testing licenses and replicate the product IDs that are used during `permission_callback`. Templates Cloud validates the license on requests when saving templates but does not provide a path just for checking license data.

My plan is to also add an endpoint that will allow TPC to check/activate/deactivate the license via Templates Cloud API. This will be used to enable or disable the PRO feature. I will save the license response as a transient inside TPC as we do with other license data. Will keep the dropdown that I just added and remove the licensing logic from TPC and replace it with some additional calls to Templates Cloud API.

The license endpoint from Templates Cloud will only accept the `license_key`, the `item_name`, `URL`, and the `action`. The `action` will only allow `activate`, `deactivate`, `check`. It will leverage the License class from `edd-sl-booster` just as we do now for allowing calls to the API.

Will also extend the `permission_callback` to allow for a Templates Cloud license, right now it only allows Neve Pro agency.

I already started working on this you can let me know if you have any feedback. Thank you!

**Comment by preda-bogdan** [comment]
@selul I created PRs for the changes discussed and asked for your review when you have time. It will now use the endpoints from Templates Cloud. I tested it locally using JSON files as found on the Live server. Should we also add a workflow so that it deploys Templates Cloud to store-staging.themeisle.com so that this can be tested by QA?

Let me know if you spot any issues or have any concerns with regard to the implementation. Looking forward to your feedback on this.

Thank you!

**Comment by selul** [comment]
@preda-bogdan I'm not sure here, we need to find a way where Irinel can test those, the simplest one works.

**Comment by JohnPixle** [comment]
Hi team 👋🏻  
I want to get more involved in this, I am deeply invested on how the styles will inter-play between themes, and want to contribute on the overall logic and workflow.

First I'd like to share some thoughts regarding what @cristian-ungureanu mentioned above:

> We will need some help from design-team to make sure the page templates we have are working smoothly with other themes as well.  **We need to edit each one of those templates and make sure we're not relying on the theme's settings (fonts/font sizes/colors) and define those inside the template.**

We will need to think deeply about this and find a meaningful workaround rather that defining styles on elements inside the templates. Below are some thoughts:

### Import Wizards, Styles and theme Inheritance

Currently all our page templates (and entire starter sites) rely heavily on the Neve customiser, from where they inherit all their styles. In order to dis-engage them from Neve, somehow we must:

👉🏻 Either "transfer" these properties (Font Family, Typographic values, color etc) into the new user's "X" theme 
 **OR** 
👉🏻 Simply let those styles inherit the defaults based on the user's theme (if it's other than Neve). 

I believe the first option is technically challenging.

**Astra**
Currently Astra Starter Templates does the same thing when used with any theme other than Astra. The typographic styles are being inherited by the theme the user is using, regardless of what font pairing or color palette you select during the import wizard.

On the last step of the wizard they prompt you to install the Astra theme and the customiser settings.

![Screenshot 2022-11-02 at 17 47 17](https://user-images.githubusercontent.com/4193672/199537777-e87ddf78-17c0-456e-be28-5531817807e5.png)


If you don't, and plan to use another theme, you won't get the font pairings and colors, but instead these will be inherited by the theme you are using.

Example: 
[Starter Site in Astra-Preview](https://websitedemos.net/earth-02/)
[Same site imported in Neve](https://absorbedact.s3-tastewp.com/)


**Kadence**
Kadence requires you to use the Kadence theme, it does not allow to import a template or starter site using any other theme.

![Screenshot 2022-11-02 at 17 42 33](https://user-images.githubusercontent.com/4193672/199534753-cab5f43a-35f5-4549-a807-6f5086be7421.png)

### Usability

From a usability and design management perspective, I strongly advise that **we avoid at all costs to define styles inline on the elements.** In this case, when the user wants to change the Style of H2 for example, he will need to go through every H2 instance and tweak the style. 

Essentially, what we are talking about to inherit from the theme (in the case of a theme other than Neve)  are:

- Body text styles
- H1-H6 styles
- Text color
- Button styles

...which personally I think are good to go, and offer the user a good baseline structure that is aligned with the preview in terms of layout. 

Let me know your thoughts on the above. Happy to start working on a rough mockup for the import wizard similar to kadence and Astra, and outline a suggested flow.

Also, it is possible that I am missing some context based on internal discussions, and be slight off on some points. If so, please let me know 🙂

**Comment by ineagu** [comment]
@JohnPixle I think there is some confusion. I see in fact 2 products : 

1. Template Patterns & Library 
2. Template Cloud.

What is particularly interesting for me is to have the cloud element theme agnostic, this is a saas that should work with any theme. You can cancel neve subscription & continue to pay for the ability to keep templates in the cloud.

So in this case if we wanna using this plugin as a "helper" plugin for the SaaS, if the user switch from Neve, or use it with a different theme, the patterns/templates/sites can be simply hidden.

There can be a separate discussion if we want theme-agnostic templates as well, but I think there should be separate patterns/templates from what we use with Neve.

@selul what do you think?

**Comment by JohnPixle** [comment]
@ineagu Some further thoughts:

If we want to focus on the Cloud storage and have it as the main value proposition, and separate the Templates/Starter Sites/patterns library, then some part of this effort should  be to aligned towards better organisation options of the material (user's uploaded assets):

- The ability for the user to organise assets in Folders / Categories
- Filtering of assets
- Automated Screenshots
- UIX for saving and managing these assets (both in GB & Elementor)

There is plenty of work to be done here.

**Comment by selul** [comment]
@JohnPixle @ineagu, thanks for sharing your thoughts. 

Yes, the way we are targeting templates cloud products right now is the ability to save any template in the cloud, no matter what theme you have. Extend the current functionality independent of Neve and use the TPC plugin as a helper plugin to facilitate the interaction with the SaaS.

The current Neve templates/starter sites will be content available to general use or restricted to people that have certain premium products of ours based on their license. The way that those general templates behave in a non-Neve environment is a different discussion that we can have once we have the mechanism independent of Neve. My idea on this is to start fresh here, with some theme-agnostic ones and consider the current ones as Neve bounded. 

> If we want to focus on the Cloud storage and have it as the main value proposition, and separate the Templates/Starter Sites/patterns library, then some part of this effort should be to aligned towards better organisation options of the material (user's uploaded assets):

That's the way to go, I agree.

**Comment by JohnPixle** [comment]
Thanks for the reply @selul !

> The way that those general templates behave in a non-Neve environment is a different discussion that we can have once we have the mechanism independent of Neve.

Ok, I will follow up when we get to that discussion. My earlier comment had to do with the flow of importing existing templates in a non-Neve environment, and based on Cristian's mention about _"...we will need some help from design-team to make sure the page templates we have are working smoothly with other themes as well."_ 

As you say we can discuss our options when we get to that point, in a different discussion. Thanks for bringing this into my attention.

Meanwhile I will take a look at the competition and similar solutions regarding how they manage the UX and flow of asset organisation.

Thanks!
