### ISSUE TITLE
increase height of images & decrease width

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/templates-patterns-collection#20]
### Description:
Right now for most of our screenshots what user sees is mostly the hero area, which is not super helpful: https://www.dropbox.com/s/fza0mv28s0t7plc/Screenshot%202020-11-06%20at%2010.54.14.png?dl=0, here is how it would look: https://www.dropbox.com/s/zzvmj2pnj8mr8w6/Screenshot%202020-11-06%20at%2011.02.14.png?dl=0.

This would allow us to take advantage of bigger screens as well, I find Astra approach here much better: https://www.dropbox.com/s/zz2emn7cnptj5dd/Screenshot%202020-11-06%20at%2011.02.44.png?dl=0, you get to see quickly 10 starter sites & see a big part of them vs how ours looks like: https://www.dropbox.com/s/072zuzdvz1mvsyu/Screenshot%202020-11-06%20at%2011.04.06.png?dl=0
### Alternatives:
do nothing

cc @selul

**Comment by ineagu** [comment]
I can see we already did that for the new template section part: https://www.dropbox.com/s/gswbbl639ky8zra/Screenshot%202020-12-10%20at%2015.47.53.png?dl=0, we can just duplicate that for starter sites as well.

**Comment by selul** [comment]
@JohnPixle @mghenciu do you have any feedback/input here?

**Comment by JohnPixle** [comment]
I'd agree with that perspective, we can definitely make use of a better aspect ratio / height of the images. I want to believe there is an efficient way to achieve this in a bulk manner, with CSS.

**Comment by abaicus** [comment]
@JohnPixle @selul @mghenciu @ineagu 


I took a shot at how this would look using the same layout as the templates page. I think it's a bit ugly, considering that it doesn't have the same visual cohesiveness (meaning colors are all over the place):

![image](https://user-images.githubusercontent.com/15010186/106282451-41bd6d00-6249-11eb-98e1-cb550b9ad2a6.png)
![image](https://user-images.githubusercontent.com/15010186/106282281-0c188400-6249-11eb-887d-34e362aa55ce.png)

I do agree that we can make the images higher on the current layout. I would also suggest increasing the spacing between the cards on screens that are larger than 1200px. What do you guys think?

![image](https://user-images.githubusercontent.com/15010186/106283780-015eee80-624b-11eb-9a60-feaa40a828f5.png)

**Comment by ineagu** [comment]
I think we can leverage more the left/right space that we have here in order to fit 4 per line with enough spacing between. ( if the screen allows).

**Comment by mghenciu** [comment]
I guess the issue with visual cohesiveness is common, when you browse themes in same things happens -> all themes have a different look & feel, making the page look like a rainbow (not in a positive way). 
One thing we can adjust later is to make sure all the thumbnails have the same aspect ratio (for example now Web Agency looks to have a different ratio compared to the other ones). And maybe customize/pick the first 8 demos, making sure they are in harmony.

For larger screens, yes, showing more demos makes sense. I think 4 (max 5) should be enough, otherwise it's hard to focus  on any of them. This happens to me on Dribbble, when I am in full-width mode
![image](https://user-images.githubusercontent.com/52494172/106288904-48e87900-6251-11eb-9f50-60a7f8e43c46.png)

**Comment by JohnPixle** [comment]
> it doesn't have the same visual cohesiveness (meaning colors are all over the place):
Yup, there is not much we can do for that, the starter sites page will always have thumbnails with different "branding" on each of them. One thing that would help, would be to increase the aspect ratios of the thumbnails, by simply adding some height.

I updated[ the figma](https://www.figma.com/file/QklXyJh0XHVzq2h4IpPNaz/Neve-options?node-id=879%3A0) with taller thumbnails. Here is how it looks.
![Screenshot 2021-01-29 at 21 42 31](https://user-images.githubusercontent.com/4193672/106320084-076cc380-627b-11eb-954a-8de954892224.png)


We should also consider if we want to have a more **full-width and "fluid" approach in the layout,** with the whole content of the Template cloud to be full-width, and with **flexible number of columns,** depending on screen size.

We can have a **minimum number of 3 columns,** that span the full-width of the browser window. Then, after a certain breakpoint we display 4 and eventually 5 columns. This way we always make use of left and right space that @ineagu mentioned.

Let me know if this makes sense :)

**Comment by abaicus** [comment]
@JohnPixle @mghenciu Tank you for your input! 

I agree with making it full width, but wouldn't that mean making the container wide for the whole page, in all views (Library, Page Templates), including the header? Otherwise, it looks weird: 

![localhost_8080_wp-admin_themes php_page=tiob-starter-sites (6)](https://user-images.githubusercontent.com/15010186/106388376-e45f2280-63e6-11eb-9013-820ce210cd86.png)

Here's am idea as to how this might look doing it:
![localhost_8080_wp-admin_themes php_page=tiob-starter-sites (5)](https://user-images.githubusercontent.com/15010186/106388236-453a2b00-63e6-11eb-885a-dadde5e3c2fa.png)

I think that for now, we can just increase the height as you changed it in figma and mabe reconsider in the future if it's worth breaking the container and making the content full width.

**Comment by tudor-themeisle** [comment]
Yes, they are bigger and showing more info about the template.
