### ISSUE TITLE
Evaluate effort of implementing WP FSE templates inside TPC.

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/templates-patterns-collection#255]
### What problem does this address?

This should allow users to import FSE templates and save FSE templates using TPC.

Challenges:
- We need to allow saving templates from FSE Editor and save metadata as options.
- Change the TPC endpoint to allow a new category for `fse-templates`, this includes saving, listing, and updating.
- Restrict `fse-templates` import for FSE Editor.

Issues that we would need to account for are that we might need to limit templates to specific themes as blocks and other template parts are tied to the theme being available.

Other considerations are tied to importing the templates, it might require a different workflow than the one we are using for the regular templates as we would replace the whole template instead of only adding some blocks.

Maybe having a designated region inside the sidebar when in FSE Editor context would be better, similar to the section we use for saving.

As a first assessment, I would evaluate the effort as a 3 or 4. While it is possible to do there still are some challenges that are not very clear.

**Comment by selul** [comment]
We can expedite this since it will be of a great use for storing templates inside templates cloud.

**Comment by cristian-ungureanu** [comment]
Hi everyone! Here's my progress so far with FSE template import into the templates cloud: https://vertis.d.pr/v/6me4Tk

To summarize the video, there are some limitations with FSE themes, the main one being the fact that FSE templates can contain template parts. If you save a template that has template parts in it, and you switch the theme, the template part will not be available in your new theme and you'll get some notices after the import ( like the ones from the video ).

After discussing this with my team, we thought that we could save the theme name somewhere and if someone wanted to import a template from a specific theme to another theme, we could either prevent it from happening or we can notice the user that some parts from the template may not be available.

Please have a look at the video and let me know your thoughts, maybe we could also improve other things from the UI.

cc @HardeepAsrani, @Codeinwp/design-team

**Comment by mghenciu** [comment]
very nice work, Cristi 🚀 and thank you for the video.

**Some thoughts:**
- would it be possible on import, to have a different name if one already exists? for example in your video, the imported template would be named Front Page 2
- for what you mentioned about Template Parts, you are right - this can be a problem and we need to inform the users about it (both on save and import). Because users are free to save them, but just need to know about the Template parts issue.
While for the templates we add, I think we can just make sure we don't include any Template Parts in them.
- for the FSE tab name, I think we were discussing this with @JohnPixle before, about maybe having both of them in the same Tab (Gutenberg), but not sure if that was the final conclusion. 

___
**Questions**
-  we could add a Toggle inside the Save Template flow: include Template Parts? and by default that would be off. But this may complicate things too much 🤔 
- I assume there's no way to automatically convert Template Parts to Static blocks on Save Template?

**Comment by cristian-ungureanu** [comment]
Thank you guys for your feedback. I've made the changes and improved a bit the saving mechanism. Here's the progress, I think I'm nearly at the end of this task: https://vertis.d.pr/v/yD6FUb

Let me know your thoughts 💭

**Comment by mghenciu** [comment]
Very nice progress, Cristi.

A few nice to have mentions:
- the naming idea is good, but if it's easy to implement; it would be nice to have it populated with the Page Name already. And if the users want to change it - they can do it.
- it would be nice to have a cookie or another mechanism that remembers the enable FSE templates Toggle. I mean the users shouldn't have to do this each time they open the import modal.
- the idea with replacing the Template Parts is very good, nice job
- if possible, **YES** - adding the TPC button in the top bar would help

Thank you!

**Comment by cristian-ungureanu** [comment]
Thank you, Mihai! I implemented all the required things from above, but I couldn't add the button at the top of the site editor. Everything you add there is overwritten after, so we'll have to stick with the import from the sidebar.
