### ISSUE TITLE
Background images from Elementor templates don't get imported 

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/templates-patterns-collection#256]
### Description

When importing a TPC Page template in Elementor, the background images are not visible, and some errors appear in the console.

### Step-by-step reproduction instructions

1. Install TPC and Elementor
2. Create a page with Elementor and insert a page template from TPC https://vertis.d.pr/i/NKolFY
3. In Elementor, there are some console errors https://vertis.d.pr/i/0cXIkC and the background image is not visible
4. On the frontend, the background image is not visible https://vertis.d.pr/i/MYJVdT
5. To fix this, you just need to edit the page in Elementor and upload a new image

### Is the issue you are reporting a regression

No

**Comment by cristian-ungureanu** [comment]
@HardeepAsrani I can't replicate this anymore, everything seems to work just fine. Maybe there was a bug in Elementor at that time.

@rodica-andronache can you give it another look and let me know if this issue is fixed?

**Comment by irinelenache** [comment]
@cristian-ungureanu I managed to replicate it, the background images are visible in editor but are not visible in frontend https://vertis.d.pr/v/mEWM4J

You can check here:
```
URL: https://xaearthworm-nusu.vertisite.cloud/elementor-144/
Username: pogofanasi0441
Password: HNZcEkjtbfuWs7a9LSw3
```

**Comment by cristian-ungureanu** [comment]
Thank you, @irinelenache. I managed to replicate the issue.
Unfortunately, I wasn't able to find a proper solution, and here's why:

After importing a template, here's how the data that Elementor uses looks like:
```
  ["background_image"]=>
  array(3) {
    ["url"]=>
    string(115) "https://api.themeisle.com/templates-data/2021/07/ebf0233ced7259cf0838b7ba6d3aee07u0xedcw82m6uywbliluq/images/bg.png"
    ["id"]=>
    int(867)
    ["size"]=>
    string(0) ""
  }
```

As you can see, there is an external URL and an image ID. Because of that ID, Elementor searches inside media post type. That is the ID of the image but on demosites, not on the current site.
I don't have access to update the templates but that's where I think the issue is.

**Comment by cristian-ungureanu** [comment]
Yes, I've tried it on my local instance.

**Comment by HardeepAsrani** [comment]
@cristian-ungureanu What are the changes required to fix it on demosites? Can you let me know so we can see if we can fix it on our end or need to update demosites

**Comment by cristian-ungureanu** [comment]
@HardeepAsrani I think we should change a demo and regenerate the export file. We should make sure the id is not returned.  I am not sure how to do this as I am not familiar with demosites. @mghenciu might be able to help.

**Comment by mghenciu** [comment]
>  @mghenciu might be able to help.

What exactly can I help with?
I can give you access to any demo, Cristi - in case this helps.

**Comment by Soare-Robert-Daniel** [comment]
I suspect that we can remove this line or a workaround: https://github.com/Codeinwp/templates-patterns-collection/blob/0c0471d887ed4d25f658422c64baf44bf1ab8687/includes/Importers/Zelle_Importer.php#L302

**Comment by Soare-Robert-Daniel** [comment]
After some investigation, the problem might not be with the process of importing the image and more with the settings of the container.

If the container is smaller than the image, a clip of the image is happening. 

In the image below, the background image is way too wide; if the container is smaller, only a portion of the image is seen.

![image](https://github.com/Codeinwp/templates-patterns-collection/assets/17597852/75fc1ccd-7388-4f82-9a22-8aaebd1c7165)

Since half of the image has one color, it creates the impression of a missing image.

If we change the image position to `center-right`, we can see this situation where the background does not feel empty.

![image](https://github.com/Codeinwp/templates-patterns-collection/assets/17597852/3ec795c0-7a6b-47a7-a8e1-0a63cd429532)

We can update the templates and make sure on the large images, the non-empty portion should be shown.

Thanks you @mghenciu, for the help with insight.
