### ISSUE TITLE
Cypress test fail

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/templates-patterns-collection#282]
### Description

After digging for some time, I've managed to find the cause of the problem.

We receive ECONNRESET on Chrome/Chromium 117.0.5851.0 when using Cypress <12.15.0

### Step-by-step reproduction instructions

- Make a PR and check the E2E tests

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
As posted on Slack, this is due to Github Action Runner being updated and using Chrome 117: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230917.1

It'll most likely not be possible to use Chrome 116 here, and the solution might be to update Cypress to a recent version. The tests work fine locally when ran using a compatible Chromium.
