### ISSUE TITLE
Old onboarding wizard is triggered when trying to import new starter sites

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/templates-patterns-collection#289]
### Description

We got an issue fixed here - https://github.com/Codeinwp/templates-patterns-collection/issues/286

So that button now works fine but if we don't use that button but we click starter sites from Neve Options we don't get to the new onboarding but I'm still a fresh user so I should get there, here is a screencast - https://vertis.d.pr/v/42iEJp

@Codeinwp/qa-team, can you comment how this was missed or it worked differently with the PR tested as the other button was also not working until it got fixed on https://github.com/Codeinwp/templates-patterns-collection/issues/286
Thank you.

### Step-by-step reproduction instructions

1. Install Neve theme
2. Go to Neve Options -> Starter Sites
3. Try to import a starter site, you get to the old onboarding wizard

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/v/42iEJp

### Is the issue you are reporting a regression

No

**Comment by rodica-andronache** [comment]
hey @vytisbulkevicius it worked the same when I tested it. It passed like this as it was not clear for me that's an issue, considering the testing instructions [here](https://github.com/Codeinwp/templates-patterns-collection/pull/269).

**Comment by vytisbulkevicius** [comment]
Hey @rodica-andronache,

Got it. But from the description for testers in that issue it should be working:

> Note for the testers: I've fixed some displaying conditions and now the onboarding lunches if:
> 
> You are a new user ( you activated neve in the last day )
> You didn't finished the import before ( you didn't click on Subscribe / Skip and view website )
> You activate Neve and have TPC installed and the above are true
> You activate TPC and have Neve installed and the above are true

or this case I described above is different?

**Comment by cristian-ungureanu** [comment]
Hey @vytisbulkevicius, thanks for bringing up this issue.

The QA team isn't at fault here because I didn't give them clear and complete instructions. I didn't do that because I wasn't entirely clear on it myself. It was more of a misunderstanding.

In the previous onboarding process, we had a parameter called `onboarding=true` that you could put in the URL of the starter sites page to view all the starter sites. If you used it, the page would load in a distraction-free fullscreen mode. 

When I fixed #286, Hardeep asked me to ensure that the old onboarding didn't appear anywhere else. So, I looked for this `onboarding=true` parameter, and I couldn't find it anywhere else, so I thought the task was done.

The misunderstanding comes from the fact that I considered the old onboarding as this environment with `onboarding=true` parameter but Hardeep referred to the actual import process.

That being said, I didn't know to ask QA to look for cases like this as our definitions of onboarding were different. 

I hope this didn't cause too much trouble. We'll fix this and make a new release ASAP.

**Comment by vytisbulkevicius** [comment]
Thanks for the explanation @cristian-ungureanu! I didn't want to sound like I'm blaming QA for this, I think each of us missed some parts and we could have done better as a team, even if instructions are not clear it's good to test different scenarios and raise questions to prevent possible issues. So let's all try to learn from this 🙏
