### ISSUE TITLE
Critical error with Medicare starter site Elementor version

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/templates-patterns-collection#328]
### Description

After importing the Elementor version of the Medicare starter site, we encountered a critical error on the site. The issue is related to the Amelia plugin that we are using in this starter site. We are able to resolve the error by disabling the plugin. 

Additionally, we noticed that the demo page of https://demosites.io/medicare/ also displays a critical error.

### Step-by-step reproduction instructions

Import the Elementor version of the Medicare starter site or check https://demosites.io/medicare/

### Screenshots, screen recording, code snippet or Help Scout ticket

On our demo page: https://vertis.d.pr/i/1dcZ9Y

On a test instance: https://vertis.d.pr/i/ABNEsH

https://secure.helpscout.net/conversation/2470268618/399157?folderId=212385

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment]
After the investigation, this was because the Amelia plugin was outdated and not working with the latest version of Elementor. 

In the newly fresh instance, the problem was not happening anymore. Only the demo site was left. Thus, the remaining fix is to update the version on the demosite, which was also done (thank you, @mghenciu, for the quick help).
