### ISSUE TITLE
Save template name in Meta

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/templates-patterns-collection#70]
We should also save _template name_ in post meta for page templates so we could allow users to change them.

**Comment by HardeepAsrani** [comment]
Right now when you save entire page, it takes the template name from the Page Title. It can become very confusing if someone publishes a template and then renames it from Library, and then updates it.

I'm unsure about the best way to manage it. What do you think @selul @mghenciu

**Comment by mghenciu** [comment]
Since I can't give a lot of technical advices, I'll just present my context and hypothesis related to this (most of them based on how I use TPC), and the story in the second part:

- Most of the time, I renamed the pages from TPC only when I did some naming mistakes (2-3 characters) 
- It feels 'natural' that the origin stays the same, even after updating the name (but maybe that's because I was doing only some minor naming fixes)
- Maybe we could store the initial name in the ID (basically a value that never changes), and the _template name_ value to be used reactive value. 
-  Expanding this to a more larger use-case (a small agency for example), I think they will use the renaming feature the same way (story below).

I am a small agency and I want to make website building faster, so I will create some rough/generic templates that will be used when starting a website. After 2 months of using those generic templates, I will create the v2 for them, meaning that the first batch will be renamed to template_name_v1. 
Looking more further, if we had a feature to Duplicate a template directly in TPC admin, then the renaming will get more complex, as it's not a small edit anymore. 

And this brings me to another point (that we can think about it later), maybe we could visually link the pages from TPC library, meaning that when I am in TPC and I want to edit a page (using an editor), how easy is for me to identify/go to that page?

**Comment by HardeepAsrani** [comment]
@mghenciu We can link Templates to Pages but normally it will be hard if people templates across different websites. Another idea can be to identify such templates and disable renaming for them but to show a tooltip notice saying "It's a page template linked to a page so you will have to rename it from the page."

What do you think?

**Comment by mghenciu** [comment]
Yes, that could work. @HardeepAsrani
