### ISSUE TITLE
importer is doubling down the woo pages on import

### ISSUE THREAD

**Issue by selul** [Codeinwp/templates-patterns-collection#95]
### Description:
It seems that for this starter site https://demosites.io/digital-store-gb/ we get two pages for shop page on import and the one from the main menu is pointing out to the non-shop page not to the one that is assigned as shop.

**Comment by preda-bogdan** [comment]
@selul I have some questions here:
From what I've tested it looks like the issue is related to the fact that the permalinks are not set during import.
Can't this be solved by updating the export.xml?

Also I can only see 2 Shop pages if WooCommerce is installed for the first time on import, should we also remove the existing Shop page from WooCommerce on import?

Please let me know. Thank you!

**Comment by selul** [comment]
@preda-bogdan that's the issue, we import two pages but we export 1.

**Comment by preda-bogdan** [comment]
@selul just a reminder, let me know when you decide if we should include the permalinks option or not on export.
Thank you!

**Comment by selul** [comment]
Lets include them automatically on export.

**Comment by preda-bogdan** [comment]
The `permalink_structure` option is now exported automatically.
